dist: xenial
before_install:
    - wget http://apertium.projectjj.com/apt/install-nightly.sh -O - | sudo bash
    - sudo apt-get install hfst apertium lttoolbox apertium-dev lttoolbox-dev libhfst-dev cg3 python3-libhfst
    - rm tests/morphophonology/test.py
    - wget https://raw.githubusercontent.com/apertium/apertium-tat/master/tests/morphophonology/test.py -O tests/morphophonology/test.py
    - ./autogen.sh
    - make
    - make check
notifications:
    irc:
        channels:
            - "chat.freenode.net#apertium"
        on_failure: change
        on_success: never
    email:
        recipients:
            - ilnar@selimcan.org
        on_failure: always
        on_success: never
